pipeline {
    agent any

    options {
        ansiColor('xterm')
    }

    parameters {
        string(name: 'ENV', defaultValue: 'PROD', description: 'which environemnt to run ')
    }

    stages {
        stage('terraform apply') {
            steps {
               dir("tera-mod") {
                sh 'make ${ENV}'
                }
            }
        }
    }
}


   stage('installing component'){
           steps{
            sh ' helm upgrade -i ${APPNAME} ./CHART  -f '
                  }
              }